# Generated by Django 4.2.11 on 2026-06-16 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorseChangeStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('interval_distance', models.FloatField(verbose_name='换马间隔（里）')),
                ('change_time', models.FloatField(default=0.5, verbose_name='换马耗时（时辰）')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': '换马策略',
                'verbose_name_plural': '换马策略',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='道路长度（里）')),
                ('slope', models.FloatField(default=0, verbose_name='坡度（度）')),
                ('grade', models.IntegerField(choices=[(1, '官道（最优）'), (2, '驿道（良好）'), (3, '乡道（一般）'), (4, '山路（较差）'), (5, '险道（极差）')], default=2, verbose_name='通行等级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '道路',
                'verbose_name_plural': '道路',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='驿站编号')),
                ('name', models.CharField(max_length=100, verbose_name='驿站名称')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '驿站',
                'verbose_name_plural': '驿站',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.IntegerField(choices=[(1, '晴朗'), (2, '多云'), (3, '小雨'), (4, '大雨'), (5, '暴雨'), (6, '小雪'), (7, '大雪'), (8, '暴雪')], default=1, verbose_name='天气类型')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='courier.road', verbose_name='道路')),
            ],
            options={
                'verbose_name': '天气记录',
                'verbose_name_plural': '天气记录',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='road',
            name='from_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads_from', to='courier.station', verbose_name='起点驿站'),
        ),
        migrations.AddField(
            model_name='road',
            name='to_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads_to', to='courier.station', verbose_name='终点驿站'),
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('priority', models.IntegerField(choices=[(1, '普通'), (2, '加急'), (3, '八百里加急')], default=1, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('executable', '可执行'), ('in_progress', '执行中'), ('completed', '已完成'), ('delayed', '已延误')], default='draft', max_length=20, verbose_name='状态')),
                ('estimated_hours', models.FloatField(blank=True, null=True, verbose_name='预计送达（时辰）')),
                ('actual_hours', models.FloatField(blank=True, null=True, verbose_name='实际送达（时辰）')),
                ('has_high_risk', models.BooleanField(default=False, verbose_name='存在高风险断点')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to', to='courier.station', verbose_name='终点驿站')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_from', to='courier.station', verbose_name='起点驿站')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier.horsechangestrategy', verbose_name='换马策略')),
            ],
            options={
                'verbose_name': '递送任务',
                'verbose_name_plural': '递送任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('segment_time', models.FloatField(blank=True, null=True, verbose_name='本段用时（时辰）')),
                ('is_high_risk', models.BooleanField(default=False, verbose_name='高风险段')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.road', verbose_name='道路段')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='courier.deliverytask', verbose_name='递送任务')),
            ],
            options={
                'verbose_name': '递送段',
                'verbose_name_plural': '递送段',
                'ordering': ['task', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='road',
            unique_together={('from_station', 'to_station')},
        ),
    ]
