# Generated by Django 4.2.11 on 2026-06-16 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('fastest', '最短送达方案'), ('safest', '最稳妥方案'), ('balanced', '均衡方案'), ('alternative', '备选方案')], max_length=20, verbose_name='方案类型')),
                ('total_time', models.FloatField(verbose_name='总耗时（时辰）')),
                ('total_distance', models.FloatField(default=0.0, verbose_name='总距离（里）')),
                ('risk_count', models.IntegerField(default=0, verbose_name='高风险段数')),
                ('station_count', models.IntegerField(default=0, verbose_name='途经驿站数')),
                ('is_delay_risk', models.BooleanField(default=False, verbose_name='存在延误风险')),
                ('delay_probability', models.FloatField(default=0.0, verbose_name='延误概率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '递送方案',
                'verbose_name_plural': '递送方案',
                'ordering': ['task', 'plan_type'],
            },
        ),
        migrations.AddField(
            model_name='deliverysegment',
            name='arrival_time',
            field=models.FloatField(blank=True, null=True, verbose_name='本段到达时间（时辰）'),
        ),
        migrations.AddField(
            model_name='deliverysegment',
            name='departure_time',
            field=models.FloatField(blank=True, null=True, verbose_name='本段出发时间（时辰）'),
        ),
        migrations.AddField(
            model_name='deliverysegment',
            name='horse_change_time',
            field=models.FloatField(blank=True, null=True, verbose_name='换马时间（时辰）'),
        ),
        migrations.AddField(
            model_name='deliverysegment',
            name='override_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_segments', to='courier.horsechangestrategy', verbose_name='本段独立换马策略'),
        ),
        migrations.AddField(
            model_name='deliverysegment',
            name='override_weather',
            field=models.IntegerField(blank=True, choices=[(1, '晴朗'), (2, '多云'), (3, '小雨'), (4, '大雨'), (5, '暴雨'), (6, '小雪'), (7, '大雪'), (8, '暴雪')], null=True, verbose_name='本段独立天气'),
        ),
        migrations.AddField(
            model_name='deliverysegment',
            name='process_time',
            field=models.FloatField(default=0.0, verbose_name='中转处理时间（时辰）'),
        ),
        migrations.AddField(
            model_name='deliverysegment',
            name='travel_time',
            field=models.FloatField(blank=True, null=True, verbose_name='行进时间（时辰）'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='deadline_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='要求时限（时辰）'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='delay_warning',
            field=models.BooleanField(default=False, verbose_name='延误预警'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='departure_offset',
            field=models.FloatField(default=0.0, verbose_name='出发时间偏移（时辰）'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='selected_plan_type',
            field=models.CharField(choices=[('fastest', '最短送达'), ('safest', '最稳妥方案'), ('balanced', '均衡方案')], default='fastest', max_length=20, verbose_name='选用方案类型'),
        ),
        migrations.AddField(
            model_name='station',
            name='capacity',
            field=models.IntegerField(default=5, verbose_name='同时处理任务数'),
        ),
        migrations.AddField(
            model_name='station',
            name='process_time',
            field=models.FloatField(default=0.2, verbose_name='中转处理耗时（时辰）'),
        ),
        migrations.CreateModel(
            name='PlanSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('segment_time', models.FloatField(verbose_name='本段用时（时辰）')),
                ('travel_time', models.FloatField(default=0.0, verbose_name='行进时间（时辰）')),
                ('horse_change_time', models.FloatField(default=0.0, verbose_name='换马时间（时辰）')),
                ('process_time', models.FloatField(default=0.0, verbose_name='中转处理时间（时辰）')),
                ('is_high_risk', models.BooleanField(default=False, verbose_name='高风险段')),
                ('departure_time', models.FloatField(blank=True, null=True, verbose_name='本段出发时间（时辰）')),
                ('arrival_time', models.FloatField(blank=True, null=True, verbose_name='本段到达时间（时辰）')),
                ('strategy_name', models.CharField(blank=True, default='', max_length=100, verbose_name='换马策略名称')),
                ('weather_display', models.CharField(blank=True, default='', max_length=50, verbose_name='天气状况')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='courier.deliveryplan', verbose_name='递送方案')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.road', verbose_name='道路段')),
            ],
            options={
                'verbose_name': '方案路段',
                'verbose_name_plural': '方案路段',
                'ordering': ['plan', 'order'],
            },
        ),
        migrations.AddField(
            model_name='deliveryplan',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='courier.deliverytask', verbose_name='递送任务'),
        ),
    ]
