# Generated by Django 4.2.11 on 2026-06-17 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_deliveryplan_deliverysegment_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='仿真名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('sim_start_time', models.FloatField(default=0.0, verbose_name='仿真起始时间（时辰）')),
                ('sim_end_time', models.FloatField(default=24.0, verbose_name='仿真结束时间（时辰）')),
                ('random_seed', models.IntegerField(default=42, verbose_name='随机种子')),
                ('task_count', models.IntegerField(default=50, verbose_name='任务数量')),
                ('enable_peak_hours', models.BooleanField(default=True, verbose_name='启用高峰时段')),
                ('priority_distribution', models.JSONField(default=dict, help_text='例如: {"1": 0.6, "2": 0.3, "3": 0.1}', verbose_name='优先级分布')),
                ('status', models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('completed', '已完成'), ('failed', '运行失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_tasks_simulated', models.IntegerField(default=0, verbose_name='已仿真任务数')),
                ('avg_wait_time', models.FloatField(blank=True, null=True, verbose_name='平均等待时长（时辰）')),
                ('max_wait_time', models.FloatField(blank=True, null=True, verbose_name='最大等待时长（时辰）')),
                ('avg_total_time', models.FloatField(blank=True, null=True, verbose_name='平均总送达时长（时辰）')),
                ('total_delay_count', models.IntegerField(default=0, verbose_name='延误任务数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '仿真运行',
                'verbose_name_plural': '仿真运行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='station',
            name='queue_rule',
            field=models.CharField(choices=[('fifo', '先进先出（无插队）'), ('priority_strict', '严格优先级（高优先级完全优先）'), ('priority_weighted', '加权优先级（高优先级概率插队）'), ('priority_class', '优先级分类（同级内先进先出）')], default='priority_class', max_length=20, verbose_name='排队插队规则'),
        ),
        migrations.AddField(
            model_name='station',
            name='window_count',
            field=models.IntegerField(default=1, verbose_name='处理窗口数量'),
        ),
        migrations.CreateModel(
            name='StationPeakHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.FloatField(verbose_name='开始时间（时辰，0-24）')),
                ('end_hour', models.FloatField(verbose_name='结束时间（时辰，0-24）')),
                ('capacity_multiplier', models.FloatField(default=0.6, verbose_name='处理能力倍率')),
                ('arrival_multiplier', models.FloatField(default=1.8, verbose_name='到达率倍率')),
                ('process_delay_pct', models.FloatField(default=30, verbose_name='处理时延增幅（%）')),
                ('label', models.CharField(blank=True, default='', max_length=50, verbose_name='时段标签')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peak_hours', to='courier.station', verbose_name='驿站')),
            ],
            options={
                'verbose_name': '驿站高峰时段',
                'verbose_name_plural': '驿站高峰时段',
                'ordering': ['station', 'start_hour'],
            },
        ),
        migrations.CreateModel(
            name='SimTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_task_code', models.CharField(max_length=50, verbose_name='仿真任务编号')),
                ('origin_id', models.IntegerField(verbose_name='起点驿站ID')),
                ('destination_id', models.IntegerField(verbose_name='终点驿站ID')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
                ('departure_time', models.FloatField(verbose_name='出发时间（时辰）')),
                ('arrival_time', models.FloatField(blank=True, null=True, verbose_name='实际送达时间（时辰）')),
                ('expected_time', models.FloatField(blank=True, null=True, verbose_name='预计送达时间（无拥堵）')),
                ('deadline', models.FloatField(blank=True, null=True, verbose_name='要求时限')),
                ('total_wait_time', models.FloatField(default=0.0, verbose_name='总等待时长（时辰）')),
                ('max_wait_at_station', models.FloatField(default=0.0, verbose_name='单站最大等待（时辰）')),
                ('station_count', models.IntegerField(default=0, verbose_name='途经驿站数')),
                ('is_delayed', models.BooleanField(default=False, verbose_name='是否延误')),
                ('delay_minutes', models.FloatField(default=0.0, verbose_name='延误时长（时辰）')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_tasks', to='courier.simulationrun', verbose_name='仿真运行')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_tasks', to='courier.deliverytask', verbose_name='关联递送任务')),
            ],
            options={
                'verbose_name': '仿真任务',
                'verbose_name_plural': '仿真任务',
                'ordering': ['simulation', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='SimStationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='驿站ID')),
                ('station_code', models.CharField(max_length=20, verbose_name='驿站编号')),
                ('visit_order', models.IntegerField(verbose_name='访问顺序')),
                ('arrive_time', models.FloatField(blank=True, null=True, verbose_name='到达时间')),
                ('queue_enter_time', models.FloatField(blank=True, null=True, verbose_name='进入排队时间')),
                ('process_start_time', models.FloatField(blank=True, null=True, verbose_name='开始处理时间')),
                ('process_end_time', models.FloatField(blank=True, null=True, verbose_name='处理完成时间')),
                ('depart_time', models.FloatField(blank=True, null=True, verbose_name='离开时间')),
                ('wait_duration', models.FloatField(default=0.0, verbose_name='排队等待时长（时辰）')),
                ('process_duration', models.FloatField(default=0.0, verbose_name='处理时长（时辰）')),
                ('queue_position_on_arrival', models.IntegerField(default=0, verbose_name='到达时队列长度')),
                ('in_peak_hour', models.BooleanField(default=False, verbose_name='是否在高峰时段')),
                ('sim_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_visits', to='courier.simtask', verbose_name='仿真任务')),
            ],
            options={
                'verbose_name': '仿真驿站访问',
                'verbose_name_plural': '仿真驿站访问',
                'ordering': ['sim_task', 'visit_order'],
            },
        ),
        migrations.CreateModel(
            name='SimStationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='驿站ID')),
                ('station_code', models.CharField(max_length=20, verbose_name='驿站编号')),
                ('snapshot_time', models.FloatField(verbose_name='快照时间（时辰）')),
                ('queue_length', models.IntegerField(default=0, verbose_name='排队长度')),
                ('busy_windows', models.IntegerField(default=0, verbose_name='忙碌窗口数')),
                ('total_windows', models.IntegerField(default=1, verbose_name='总窗口数')),
                ('utilization', models.FloatField(default=0.0, verbose_name='利用率（%）')),
                ('in_peak_hour', models.BooleanField(default=False, verbose_name='是否在高峰时段')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_snapshots', to='courier.simulationrun', verbose_name='仿真运行')),
            ],
            options={
                'verbose_name': '驿站快照',
                'verbose_name_plural': '驿站快照',
                'ordering': ['simulation', 'station_id', 'snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='SimBottleneckStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='驿站ID')),
                ('station_code', models.CharField(max_length=20, verbose_name='驿站编号')),
                ('station_name', models.CharField(max_length=100, verbose_name='驿站名称')),
                ('total_visits', models.IntegerField(default=0, verbose_name='总访问次数')),
                ('avg_wait_time', models.FloatField(default=0.0, verbose_name='平均等待时长（时辰）')),
                ('max_wait_time', models.FloatField(default=0.0, verbose_name='最大等待时长（时辰）')),
                ('total_wait_time', models.FloatField(default=0.0, verbose_name='累计等待时长（时辰）')),
                ('avg_queue_length', models.FloatField(default=0.0, verbose_name='平均排队长度')),
                ('max_queue_length', models.IntegerField(default=0, verbose_name='最大排队长度')),
                ('avg_utilization', models.FloatField(default=0.0, verbose_name='平均利用率（%）')),
                ('peak_queue_count', models.IntegerField(default=0, verbose_name='高峰拥堵次数')),
                ('bottleneck_score', models.FloatField(default=0.0, verbose_name='瓶颈评分')),
                ('rank', models.IntegerField(default=0, verbose_name='瓶颈排名')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottleneck_stations', to='courier.simulationrun', verbose_name='仿真运行')),
            ],
            options={
                'verbose_name': '瓶颈驿站',
                'verbose_name_plural': '瓶颈驿站',
                'ordering': ['simulation', 'rank'],
            },
        ),
    ]
