# Generated by Django 4.2.11 on 2026-06-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_simulationrun_station_queue_rule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadBlockadeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('road_blocked', '道路封锁'), ('road_restricted', '半封闭限流'), ('station_down', '驿站停摆'), ('military_priority', '军务优先通行')], max_length=25, verbose_name='事件类型')),
                ('name', models.CharField(max_length=200, verbose_name='事件名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('start_hour', models.FloatField(verbose_name='开始时间（时辰，0-24）')),
                ('end_hour', models.FloatField(verbose_name='结束时间（时辰，0-24）')),
                ('severity', models.FloatField(default=1.0, verbose_name='严重程度（1-10）')),
                ('flow_rate', models.FloatField(default=0.0, verbose_name='通行率（0=完全封锁，1=正常通行）')),
                ('reroute_cost_multiplier', models.FloatField(default=1.0, verbose_name='改道成本倍率')),
                ('military_priority_level', models.IntegerField(default=3, verbose_name='军务优先等级（1-3）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockade_events', to='courier.road', verbose_name='影响道路')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockade_events', to='courier.station', verbose_name='影响驿站')),
            ],
            options={
                'verbose_name': '封锁事件',
                'verbose_name_plural': '封锁事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockadeDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='推演名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('pending', '待推演'), ('running', '推演中'), ('completed', '已完成'), ('failed', '推演失败')], default='pending', max_length=20, verbose_name='状态')),
                ('before_avg_wait', models.FloatField(blank=True, null=True, verbose_name='封锁前平均等待(时辰)')),
                ('before_max_wait', models.FloatField(blank=True, null=True, verbose_name='封锁前最大等待(时辰)')),
                ('before_avg_total', models.FloatField(blank=True, null=True, verbose_name='封锁前平均送达(时辰)')),
                ('before_delay_count', models.IntegerField(blank=True, null=True, verbose_name='封锁前延误数')),
                ('before_bottleneck_codes', models.JSONField(default=list, verbose_name='封锁前瓶颈驿站列表')),
                ('after_avg_wait', models.FloatField(blank=True, null=True, verbose_name='封锁后平均等待(时辰)')),
                ('after_max_wait', models.FloatField(blank=True, null=True, verbose_name='封锁后最大等待(时辰)')),
                ('after_avg_total', models.FloatField(blank=True, null=True, verbose_name='封锁后平均送达(时辰)')),
                ('after_delay_count', models.IntegerField(blank=True, null=True, verbose_name='封锁后延误数')),
                ('after_bottleneck_codes', models.JSONField(default=list, verbose_name='封锁后瓶颈驿站列表')),
                ('reroute_cost_total', models.FloatField(default=0.0, verbose_name='总改道成本')),
                ('affected_task_count', models.IntegerField(default=0, verbose_name='受影响任务数')),
                ('congestion_transfer', models.JSONField(default=dict, verbose_name='拥堵转移数据')),
                ('impact_timeline', models.JSONField(default=list, verbose_name='事件影响时间轴')),
                ('recovery_strategies', models.JSONField(default=list, verbose_name='恢复策略建议')),
                ('bottleneck_diff', models.JSONField(default=dict, verbose_name='瓶颈变化对比')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('base_simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockade_drills', to='courier.simulationrun', verbose_name='基准仿真')),
                ('blockade_events', models.ManyToManyField(related_name='drills', to='courier.roadblockadeevent', verbose_name='封锁事件')),
            ],
            options={
                'verbose_name': '封锁推演',
                'verbose_name_plural': '封锁推演',
                'ordering': ['-created_at'],
            },
        ),
    ]
